services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
    driver: local
