services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql

  dev:
    build:
      context: ./
    networks:
      - mynet
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command:
      - nodemon
      - ./dist/index.js
    links:
      - db
    restart: always

networks:
  mynet:
    driver: bridge

volumes:
  data:
    driver: local
